print("Complete Name: Francis Alfred R. Rabanes")
print("Course: BSCS")
print("Section: CS1E")
print("Age: 21 Years Old")
print("Birthday: July 30, 2002")
print("Complete Home Address: Xavier Heights Block 32 Lot 7 Balulang Cagayan De Oro City Misamis Oriental")

print("Enter the Following details: ")
name = input("Youre Complete Name? ")
course = input("Youre Course? ")
section = input("Youre Section? ")
age = input("Youre Age? ")
bday = input("Youre Birthday? ")
home = input("Youre Complete Home Address? ")

print("Complete Name:" , name)
print("Course:" , course)
print("Section:" , section)
print("Age:" , age)
print("Birthday:" , bday)
print("Complete Home Address:" , home)